# Generated by Django 4.2.2 on 2023-06-16 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '__first__'),
        ('albums', '0003_alter_album_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersongalbum',
            unique_together={('album_id', 'song_id')},
        ),
    ]
