# Generated by Django 4.2.2 on 2023-07-05 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('albums', '0004_alter_usersongalbum_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSongAlbum',
            new_name='AlbumSong',
        ),
        migrations.RenameModel(
            old_name='UserFollowAlbum',
            new_name='Follower',
        ),
    ]
