# Generated by Django 4.2.2 on 2023-06-15 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='created_date',
        ),
        migrations.AddField(
            model_name='song',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 15, 14, 45, 24, 904619)),
        ),
    ]
