# Generated by Django 4.2.2 on 2023-06-16 10:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0003_alter_song_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='created_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name='usersongfavorite',
            unique_together={('user_id', 'song_id')},
        ),
    ]
