# Generated by Django 4.2.2 on 2023-07-05 14:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0004_alter_song_created_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSongComment',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='UserSongFavorite',
            new_name='Favorite',
        ),
        migrations.RenameModel(
            old_name='UserSongLike',
            new_name='Like',
        ),
        migrations.RemoveField(
            model_name='userfollowalbum',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='userfollowalbum',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='usersongalbum',
            name='album_id',
        ),
        migrations.RemoveField(
            model_name='usersongalbum',
            name='song_id',
        ),
        migrations.RemoveField(
            model_name='usersongalbum',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='UserFollowAlbum',
        ),
        migrations.DeleteModel(
            name='UserSongAlbum',
        ),
    ]
